import { API_URL } from "@zoonk/utils/url";
import { getNextLesson } from "./get-next-lesson";

/**
 * Best-effort preloading of the next lesson's content.
 * Skips the HTTP call when the next lesson is already generated
 * or currently being generated by another workflow run.
 * Silently ignores errors since preloading is an optimization.
 */
export async function preloadNextLesson(activityId: bigint, cookieHeader: string): Promise<void> {
  const nextLesson = await getNextLesson(activityId);

  if (!nextLesson || !nextLesson.needsGeneration) {
    return;
  }

  try {
    await fetch(`${API_URL}/v1/workflows/lesson-preload/trigger`, {
      body: JSON.stringify({ lessonId: nextLesson.id }),
      headers: {
        "Content-Type": "application/json",
        Cookie: cookieHeader,
      },
      method: "POST",
    });
  } catch {
    // Preloading is best-effort; silently ignore errors.
  }
}
