import { physicsCourse } from "../../library/physics/physics-course";
import { type SeedLearner } from "../types";

/**
 * A huge learn goal: quantum physics from scratch at 45 minutes a day, in five phases.
 * Her skill graph sizes skills the way the graph task does for a huge goal (chapter-sized, up to
 * 60 lessons each), so most of their lessons aren't outlined yet and the plan runs for months.
 * Placement let her skip fractions and equations, all 48 of their lessons; she's in phase 1, the
 * math.
 */
export const mayaHugeGoal: SeedLearner = {
  attempts: [
    {
      answer: { selectedIndex: 1 },
      day: -1,
      isCorrect: false,
      item: "negative-power",
      key: "negative-power",
      mistake: {
        cause: "gap",
        snapshot: {
          answer: "−1,000",
          correctAnswer: "0.001",
          explanation: "A negative power makes a small number, never a negative one.",
          format: "multipleChoice",
          misconception: "Thinks a negative power makes a negative number",
          question: "What is 10⁻³?",
        },
        status: "open",
      },
      seconds: 29,
      skill: "powers-of-ten",
    },
    {
      answer: { isTrue: true },
      day: 0,
      inSession: true,
      isCorrect: true,
      item: "three-quarters",
      key: "review-fraction",
      seconds: 9,
      skill: "fractions",
    },
    {
      answer: { selectedIndex: 0 },
      day: 0,
      inSession: true,
      isCorrect: true,
      item: "thirty-percent",
      key: "review-percent",
      seconds: 14,
      skill: "percent-of",
    },
    {
      answer: { selectedOptionId: "right" },
      day: 0,
      inSession: true,
      isCorrect: true,
      key: "sci-notation-small-number",
      seconds: 21,
      skill: "sci-notation",
      step: { lesson: "scientific-notation", position: 3 },
    },
  ],
  brainPower: 3340,
  email: "v2-learn@zoonk.test",
  feedback: [{ item: "thirty-percent", kind: "item", vote: "up" }],
  goal: {
    course: physicsCourse,
    createdDay: -24,
    dailyMinutes: 45,
    details: {
      level: "nothing yet",
      purpose: "deep",
      reason: "Wants to read papers about quantum computers",
    },
    key: "quantum",
    kind: "learn",
    plan: {
      changes: [
        {
          day: -24,
          kind: "testedOut",
          payload: { lessons: 48, source: "placement" },
          reason:
            "You already know fractions and linear equations, so the plan skips their 48 lessons.",
        },
      ],
      items: [
        {
          chapter: "fractions-percentages",
          day: -24,
          kind: "chapter",
          phase: 0,
          status: "testedOut",
        },
        { chapter: "linear-equations", day: -24, kind: "chapter", phase: 0, status: "testedOut" },
        { day: -21, kind: "lesson", lesson: "function-machine", phase: 0, status: "done" },
        { day: -12, kind: "lesson", lesson: "reading-graphs", phase: 0, status: "done" },
        { day: -4, kind: "lesson", lesson: "slope-is-a-rate", phase: 0, status: "done" },
        { day: -1, kind: "lesson", lesson: "powers-of-ten", phase: 0, status: "done" },
        { day: 0, kind: "lesson", lesson: "scientific-notation", phase: 0, status: "todo" },
        { day: 0, kind: "lesson", lesson: "multiply-divide-powers", phase: 0, status: "todo" },
        { chapter: "vectors", day: 3, kind: "chapter", phase: 0, status: "todo" },
        { chapter: "derivatives", kind: "chapter", phase: 1, status: "todo" },
        { chapter: "integrals", kind: "chapter", phase: 1, status: "todo" },
        { chapter: "motion-forces", kind: "chapter", phase: 2, status: "todo" },
        { chapter: "waves", kind: "chapter", phase: 2, status: "todo" },
        { chapter: "electricity-magnetism", kind: "chapter", phase: 2, status: "todo" },
        { chapter: "inside-the-atom", kind: "chapter", phase: 3, status: "todo" },
        { chapter: "wave-function", kind: "chapter", phase: 3, status: "todo" },
        { chapter: "schrodinger-equation", kind: "chapter", phase: 3, status: "todo" },
        { chapter: "spin", kind: "chapter", phase: 4, status: "todo" },
        { chapter: "quantum-computing", kind: "chapter", phase: 4, status: "todo" },
      ],
      phases: [
        { milestone: "Solve equations and use vectors", name: "The math physics uses" },
        {
          milestone: "Differentiate, integrate and use matrices",
          name: "Calculus and linear algebra",
        },
        { milestone: "Motion, waves and electricity", name: "Classical physics" },
        { milestone: "The atom and the Schrödinger equation", name: "Quantum mechanics" },
        { milestone: "Spin, entanglement and computing", name: "Advanced quantum physics" },
      ],
      skillLessons: {
        "atom-structure": 25,
        "bell-test": 50,
        "born-rule": 60,
        confinement: 40,
        derivative: 60,
        "derivative-rules": 60,
        "electric-field": 60,
        "electron-cloud": 40,
        "em-wave": 50,
        "emission-lines": 30,
        "energy-conservation": 60,
        fractions: 10,
        "function-concept": 20,
        "ground-state": 30,
        "hydrogen-levels": 60,
        integral: 60,
        interference: 50,
        "model-equation": 15,
        "newton-second-law": 60,
        "orders-of-magnitude": 10,
        "particle-in-box": 60,
        "percent-of": 8,
        "photon-wavelength": 25,
        "powers-of-ten": 12,
        qubit: 60,
        "read-graph": 15,
        "sci-notation": 15,
        "sci-operations": 15,
        slope: 20,
        "solve-linear": 15,
        spin: 60,
        superposition: 50,
        "vector-add": 30,
        "vector-concept": 20,
        "wave-equation": 45,
      },
    },
    prompt: "I want to master quantum physics, starting from scratch",
    studyTime: "07:30",
    title: "Master quantum physics, from scratch",
  },
  history: { accuracy: 0.82, days: 24, energy: 76, minutesPerDay: 42, skipChance: 0.15 },
  key: "maya",
  language: "en",
  memory: [
    {
      category: "goals",
      origin: "said",
      statement: "Wants to read papers about quantum computers",
    },
    {
      category: "background",
      origin: "said",
      statement: "Works as a nurse, mostly on night shifts",
    },
    {
      category: "routine",
      origin: "said",
      statement: "Studies at 7:30 am, right after a night shift",
    },
    {
      category: "learning",
      origin: "noticed",
      statement: "Does better with a worked example before trying alone",
    },
  ],
  milestones: [{ day: -6, key: "yellow", kind: "belt", shown: true }],
  name: "Maya Chen",
  plus: true,
  session: {
    blocks: [
      {
        brainPower: 25,
        capsules: [
          { items: ["three-quarters"], skills: ["fractions"], title: "Fractions and percentages" },
          {
            items: ["thirty-percent"],
            skills: ["percent-of"],
            title: "Finding a percent of a number",
          },
        ],
        kind: "review",
        minutes: 6,
        status: "completed",
      },
      { kind: "learn", lesson: "scientific-notation", minutes: 12, status: "active" },
      {
        drills: [{ items: ["negative-power"], mistake: "negative-power" }],
        items: ["sci-notation-moon", "orders-of-magnitude-ratio"],
        kind: "practice",
        minutes: 12,
        status: "pending",
        title: "Practice with powers of ten",
      },
      { kind: "learn", lesson: "multiply-divide-powers", minutes: 15, status: "pending" },
    ],
    status: "active",
  },
  skills: [
    { memory: "mastered", skill: "fractions" },
    { memory: "mastered", skill: "percent-of" },
    { memory: "solid", skill: "solve-linear" },
    { memory: "solid", skill: "model-equation" },
    { memory: "solid", skill: "function-concept" },
    { memory: "fading", skill: "read-graph" },
    { memory: "learning", skill: "slope" },
    { memory: "learning", skill: "powers-of-ten" },
    { memory: "learning", skill: "sci-notation" },
  ],
  timeZone: "America/New_York",
  username: "maya_learns",
};
