packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/client"
  - cbor-extract
  - sharp

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma
