packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma

ignoredBuiltDependencies:
  - "@prisma/client"
  - sharp
