packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/client"
  - cbor-extract
  - sharp

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@sentry/cli"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma
overrides:
  "@hono/node-server@<1.19.10": ">=1.19.10"
  "@types/pg": 8.18.0
  file-type@>=13.0.0 <21.3.1: ">=21.3.1"
  hono@<4.11.10: ">=4.11.10"
  hono@<4.11.7: ">=4.11.7"
  hono@<4.12.4: ">=4.12.4"
  hono@<4.12.7: ">=4.12.7"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  serialize-javascript@<=7.0.2: ">=7.0.3"
