packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/client"
  - cbor-extract
  - sharp

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - prisma

overrides:
  fast-xml-parser@<5.3.8: ">=5.3.8"
  hono@<4.11.10: ">=4.11.10"
  hono@<4.11.7: ">=4.11.7"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
