import { streamSkipStep } from "@/workflows/_shared/stream-skip-step";
import { serializeWorkflowError } from "@/workflows/_shared/workflow-error";
import { handleChapterFailureStep } from "@/workflows/course-generation/steps/handle-failure-step";
import { CHAPTER_COMPLETION_STEP } from "@zoonk/core/workflows/steps";
import { type Lesson } from "@zoonk/db";
import { getWorkflowMetadata } from "workflow";
import {
  type ExpandedChapterLesson,
  expandChapterLessons,
} from "./steps/_utils/lesson-plan-expansion";
import { addLessonsStep } from "./steps/add-lessons-step";
import { classifyLessonsStep } from "./steps/classify-lessons-step";
import { generateLessonsStep } from "./steps/generate-lessons-step";
import { getChapterGenerationTargetLanguage, getChapterStep } from "./steps/get-chapter-step";
import { setChapterAsCompletedStep } from "./steps/set-chapter-as-completed-step";
import { setChapterAsRunningStep } from "./steps/set-chapter-as-running-step";

async function generateExpandedLessons(
  context: Awaited<ReturnType<typeof getChapterStep>>,
): Promise<ExpandedChapterLesson[]> {
  const plan = await generateLessonsStep(context);
  const lessons = await classifyLessonsStep({ context, plan });

  return expandChapterLessons({
    lessons,
    targetLanguage: getChapterGenerationTargetLanguage(context.course),
  });
}

/**
 * Creates the lesson rows, then marks the chapter as completed. Chapter
 * thumbnails are generated by the parent course workflow so image failures do
 * not block chapter lesson planning.
 */
async function generateLessonsAndCompleteChapter({
  context,
  workflowRunId,
}: {
  context: Awaited<ReturnType<typeof getChapterStep>>;
  workflowRunId: string;
}): Promise<Lesson[]> {
  const lessons = await generateExpandedLessons(context);
  const createdLessons = await addLessonsStep({ context, lessons });

  await setChapterAsCompletedStep({ context, workflowRunId });

  return createdLessons;
}

export async function chapterGenerationWorkflow(chapterId: string): Promise<void> {
  "use workflow";

  const { workflowRunId } = getWorkflowMetadata();

  // Fetch chapter data (throws FatalError if not found)
  const context = await getChapterStep(chapterId);

  // Skip if actively running to avoid conflicts with another workflow instance.
  if (context.generationStatus === "running") {
    return;
  }

  // Already completed — stream the completion step so the client can redirect.
  if (context.generationStatus === "completed") {
    await streamSkipStep(CHAPTER_COMPLETION_STEP);
    return;
  }

  // Mark chapter as running
  const isClaimed = await setChapterAsRunningStep({ chapterId, workflowRunId });

  if (!isClaimed) {
    return;
  }

  // A recovered complete plan still claims the chapter before repairing its status.
  if (context._count.lessons > 0) {
    await setChapterAsCompletedStep({
      context: { ...context, generationRunId: workflowRunId },
      workflowRunId,
    });

    return;
  }

  // Chapter-specific work with failure handling
  await generateLessonsAndCompleteChapter({
    context: { ...context, generationRunId: workflowRunId },
    workflowRunId,
  }).catch(async (error: unknown) => {
    await handleChapterFailureStep({
      chapterId,
      error: serializeWorkflowError(error),
      workflowRunId,
    });

    throw error;
  });
}
