import { streamSkipStep } from "@/workflows/_shared/stream-skip-step";
import { serializeWorkflowError } from "@/workflows/_shared/workflow-error";
import { handleChapterFailureStep } from "@/workflows/course-generation/steps/handle-failure-step";
import { lessonGenerationWorkflow } from "@/workflows/lesson-generation/lesson-generation-workflow";
import { isStandaloneGeneratedLessonKind } from "@zoonk/core/lessons/generated-companion-kinds";
import { CHAPTER_COMPLETION_STEP } from "@zoonk/core/workflows/steps";
import { type Lesson } from "@zoonk/db";
import { getWorkflowMetadata } from "workflow";
import {
  type ExpandedChapterLesson,
  expandChapterLessons,
} from "./steps/_utils/lesson-plan-expansion";
import { addLessonsStep } from "./steps/add-lessons-step";
import { classifyLessonsStep } from "./steps/classify-lessons-step";
import { generateLessonsStep } from "./steps/generate-lessons-step";
import { getChapterStep } from "./steps/get-chapter-step";
import { setChapterAsCompletedStep } from "./steps/set-chapter-as-completed-step";
import { setChapterAsRunningStep } from "./steps/set-chapter-as-running-step";

const INITIAL_LESSON_GENERATION_TARGET_COUNT = 3;

async function generateExpandedLessons(
  context: Awaited<ReturnType<typeof getChapterStep>>,
): Promise<ExpandedChapterLesson[]> {
  const plan = await generateLessonsStep(context);
  const lessons = await classifyLessonsStep({ context, plan });

  return expandChapterLessons({ lessons, targetLanguage: context.course.targetLanguage });
}

/**
 * Creates the lesson rows, then marks the chapter as completed. Chapter
 * thumbnails are generated by the parent course workflow so image failures do
 * not block chapter lesson planning.
 */
async function generateLessonsAndCompleteChapter({
  context,
  workflowRunId,
}: {
  context: Awaited<ReturnType<typeof getChapterStep>>;
  workflowRunId: string;
}): Promise<Lesson[]> {
  const lessons = await generateExpandedLessons(context);
  const createdLessons = await addLessonsStep({ context, lessons });

  await setChapterAsCompletedStep({ context, workflowRunId });

  return createdLessons;
}

/**
 * Initial lesson generation should warm up the first standalone lesson
 * workflows without serializing on each one. Translation and listening rows are
 * materialized by vocabulary and reading generation, respectively.
 */
async function generateInitialLessons(createdLessons: Lesson[]): Promise<void> {
  const initialLessons = createdLessons
    .filter((lesson) => isStandaloneGeneratedLessonKind(lesson.kind))
    .slice(0, INITIAL_LESSON_GENERATION_TARGET_COUNT);

  await Promise.allSettled(initialLessons.map((lesson) => lessonGenerationWorkflow(lesson.id)));
}

export async function chapterGenerationWorkflow(chapterId: string): Promise<void> {
  "use workflow";

  const { workflowRunId } = getWorkflowMetadata();

  // Fetch chapter data (throws FatalError if not found)
  const context = await getChapterStep(chapterId);

  // Skip if actively running to avoid conflicts with another workflow instance.
  if (context.generationStatus === "running") {
    return;
  }

  // Already completed — stream the completion step so the client can redirect.
  if (context.generationStatus === "completed") {
    await streamSkipStep(CHAPTER_COMPLETION_STEP);
    return;
  }

  // If chapter has lessons but status is not completed, fix the status
  if (context._count.lessons > 0) {
    await setChapterAsCompletedStep({ context, workflowRunId });

    return;
  }

  // Mark chapter as running
  const isClaimed = await setChapterAsRunningStep({ chapterId, workflowRunId });

  if (!isClaimed) {
    return;
  }

  // Chapter-specific work with failure handling
  const createdLessons = await generateLessonsAndCompleteChapter({ context, workflowRunId }).catch(
    async (error: unknown) => {
      await handleChapterFailureStep({ chapterId, error: serializeWorkflowError(error) });

      throw error;
    },
  );

  // Generate the initial standalone lessons outside chapter failure handling so
  // lesson failures do not roll back the completed chapter plan.
  await generateInitialLessons(createdLessons);
}
