import { generateStepContentImage } from "@zoonk/ai/tasks/steps/content-image";
import sharp from "sharp";
import { describe, expect, it, vi } from "vitest";
import { uploadImage } from "../images/upload-image";
import { generateContentStepImage } from "./step-content-image";

vi.mock("@zoonk/ai/tasks/steps/content-image", () => ({ generateStepContentImage: vi.fn() }));

vi.mock("../images/upload-image", () => ({ uploadImage: vi.fn() }));

/**
 * Creates tiny deterministic images so the retry behavior can be tested
 * without calling the image model or relying on fixture files.
 */
async function createSolidWebp({ blue, green, red }: { blue: number; green: number; red: number }) {
  return sharp({
    create: { background: `rgb(${red}, ${green}, ${blue})`, channels: 3, height: 32, width: 32 },
  })
    .webp()
    .toBuffer();
}

/**
 * Creates a simple image with visible contrast so the blank-image guard can
 * distinguish real image content from a full-frame solid color.
 */
async function createTwoColorWebp() {
  const leftHalf = await sharp({
    create: { background: "rgb(255, 255, 255)", channels: 3, height: 32, width: 16 },
  })
    .webp()
    .toBuffer();

  const rightHalf = await sharp({
    create: { background: "rgb(24, 96, 180)", channels: 3, height: 32, width: 16 },
  })
    .webp()
    .toBuffer();

  return sharp({ create: { background: "rgb(255, 255, 255)", channels: 3, height: 32, width: 32 } })
    .composite([
      { input: leftHalf, left: 0, top: 0 },
      { input: rightHalf, left: 16, top: 0 },
    ])
    .webp()
    .toBuffer();
}

/**
 * Creates an image that is mostly one quiet background color but still has a
 * small meaningful mark. Real lesson illustrations can be sparse, so the guard
 * should only reject fully blank output, not minimal icon-like compositions.
 */
async function createMostlySolidIconWebp() {
  const icon = await sharp({
    create: { background: "rgb(24, 96, 180)", channels: 3, height: 4, width: 4 },
  })
    .webp()
    .toBuffer();

  return sharp({ create: { background: "rgb(255, 255, 255)", channels: 3, height: 32, width: 32 } })
    .composite([{ input: icon, left: 14, top: 14 }])
    .webp()
    .toBuffer();
}

/**
 * The AI SDK exposes generated bytes through `uint8Array`; the production code
 * only needs those bytes before optimization, so the tests keep the fake file
 * deliberately small.
 */
function createGeneratedFile(image: Buffer) {
  return {
    base64: image.toString("base64"),
    mediaType: "image/webp" as const,
    uint8Array: new Uint8Array(image),
  };
}

describe(generateContentStepImage, () => {
  it("retries solid-color generated images before uploading", async () => {
    const blankImage = await createSolidWebp({ blue: 255, green: 64, red: 32 });
    const visibleImage = await createTwoColorWebp();

    vi.mocked(generateStepContentImage)
      .mockResolvedValueOnce({ data: createGeneratedFile(blankImage), error: null })
      .mockResolvedValueOnce({ data: createGeneratedFile(visibleImage), error: null });

    vi.mocked(uploadImage).mockResolvedValueOnce({
      data: "https://example.com/visible-step.webp",
      error: null,
    });

    const result = await generateContentStepImage({
      language: "pt",
      prompt: "Ilustração de uma folha com manchas marrons observáveis.",
    });

    expect(result).toStrictEqual({ data: "https://example.com/visible-step.webp", error: null });
    expect(generateStepContentImage).toHaveBeenCalledTimes(2);
    expect(uploadImage).toHaveBeenCalledOnce();
  });

  it("uploads mostly solid images when they include a small visible element", async () => {
    const imageWithIcon = await createMostlySolidIconWebp();

    vi.mocked(generateStepContentImage).mockResolvedValueOnce({
      data: createGeneratedFile(imageWithIcon),
      error: null,
    });

    vi.mocked(uploadImage).mockResolvedValueOnce({
      data: "https://example.com/minimal-step.webp",
      error: null,
    });

    const result = await generateContentStepImage({
      language: "pt",
      prompt: "Ícone pequeno no centro de uma tela branca.",
    });

    expect(result).toStrictEqual({ data: "https://example.com/minimal-step.webp", error: null });
    expect(generateStepContentImage).toHaveBeenCalledOnce();
    expect(uploadImage).toHaveBeenCalledOnce();
  });

  it("returns an error when every generated image is a solid color", async () => {
    const blackImage = await createSolidWebp({ blue: 0, green: 0, red: 0 });
    const whiteImage = await createSolidWebp({ blue: 255, green: 255, red: 255 });

    vi.mocked(generateStepContentImage)
      .mockResolvedValueOnce({ data: createGeneratedFile(blackImage), error: null })
      .mockResolvedValueOnce({ data: createGeneratedFile(whiteImage), error: null });

    const result = await generateContentStepImage({
      language: "pt",
      prompt: "Ilustração de uma folha com manchas marrons observáveis.",
    });

    expect(result.data).toBeNull();
    expect(result.error?.message).toBe("Generated image was near-solid color");
    expect(generateStepContentImage).toHaveBeenCalledTimes(2);
    expect(uploadImage).not.toHaveBeenCalled();
  });
});
