import { MediaCardPopoverAIWarning } from "@zoonk/ui/components/media-card";
import { AI_ORG_SLUG } from "@zoonk/utils/constants";
import { getExtracted } from "next-intl/server";

export async function AIWarning({ brandSlug }: { brandSlug: string }) {
  if (brandSlug !== AI_ORG_SLUG) {
    return null;
  }

  const t = await getExtracted();

  return (
    <MediaCardPopoverAIWarning className="mb-3">
      {t(
        "This content was generated by AI. It may contain errors or inaccuracies and should not be considered professional advice.",
      )}
    </MediaCardPopoverAIWarning>
  );
}
