import { toSlug } from "@zoonk/utils/string";

type AiVisualDiagramOutput = {
  edges: { from: string; label: string | null; to: string }[];
  nodes: { label: string }[];
};

type VisualDiagramOutput = {
  edges: { label: string | null; source: string; target: string }[];
  nodes: { id: string; label: string }[];
};

const GENERATED_NODE_ID_PREFIX = "diagram-node";
const UNMATCHED_NODE_ID = "unmatched-diagram-node";

/**
 * Diagram labels are learner-facing text, so they can legitimately be
 * punctuation-only tokens such as `( )` or `"`. `toSlug` turns those into an
 * empty string, which later crashes the player layout. This helper guarantees
 * that every saved node id is non-empty and unique without changing the label.
 */
function createDiagramNodeId({
  index,
  label,
  takenIds,
}: {
  index: number;
  label: string;
  takenIds: Set<string>;
}): string {
  const baseId = toSlug(label) || `${GENERATED_NODE_ID_PREFIX}-${index + 1}`;
  return claimUniqueDiagramNodeId({ baseId, takenIds });
}

/**
 * Distinct diagram nodes need distinct ids even when two labels normalize to
 * the same slug. Keeping the uniqueness rule here avoids duplicating suffix
 * logic in every caller that creates diagram node ids.
 */
function claimUniqueDiagramNodeId({
  baseId,
  takenIds,
}: {
  baseId: string;
  takenIds: Set<string>;
}): string {
  if (!takenIds.has(baseId)) {
    takenIds.add(baseId);
    return baseId;
  }

  let suffix = 2;
  let candidate = `${baseId}-${suffix}`;

  while (takenIds.has(candidate)) {
    suffix += 1;
    candidate = `${baseId}-${suffix}`;
  }

  takenIds.add(candidate);
  return candidate;
}

/**
 * When an edge points to a label that does not exist in the node list, we keep
 * the diagram usable by inventing a fallback id. Punctuation-only labels still
 * need a non-empty placeholder so the saved graph stays valid.
 */
function createUnmatchedDiagramNodeId({ label }: { label: string }): string {
  return toSlug(label) || UNMATCHED_NODE_ID;
}

/**
 * Edge labels generated by the model often differ slightly from the
 * matching node labels because of casing or partial wording. This
 * resolver tries the obvious matches first and only falls back to a
 * slug when the edge truly points to something missing, which keeps
 * the final diagram usable instead of breaking on minor wording drift.
 */
function isWholeWordExtensionMatch({
  candidateLabel,
  edgeLabel,
}: {
  candidateLabel: string;
  edgeLabel: string;
}): boolean {
  const candidateSlug = toSlug(candidateLabel);
  const edgeSlug = toSlug(edgeLabel);

  return (
    candidateSlug.startsWith(`${edgeSlug}-`) ||
    candidateSlug.endsWith(`-${edgeSlug}`) ||
    edgeSlug.startsWith(`${candidateSlug}-`) ||
    edgeSlug.endsWith(`-${candidateSlug}`)
  );
}

/**
 * Edge labels generated by the model often differ slightly from the
 * matching node labels because of casing or extra leading or trailing
 * words. This resolver tries the obvious matches first and only falls
 * back to a slug when the edge truly points to something missing, which
 * keeps the final diagram usable without letting arbitrary substrings
 * snap to the wrong node.
 */
function resolveNodeId({
  edgeLabel,
  nodeMap,
  takenIds,
  unmatchedNodeIds,
}: {
  edgeLabel: string;
  nodeMap: Map<string, string>;
  takenIds: Set<string>;
  unmatchedNodeIds: Map<string, string>;
}): string {
  const directMatch = nodeMap.get(edgeLabel);

  if (directMatch) {
    return directMatch;
  }

  const normalizedEdgeLabel = edgeLabel.toLowerCase();
  const nodeEntries = [...nodeMap];

  const caseInsensitiveMatch = nodeEntries.find(
    ([label]) => label.toLowerCase() === normalizedEdgeLabel,
  );

  if (caseInsensitiveMatch) {
    return caseInsensitiveMatch[1];
  }

  const substringMatch = nodeEntries.find(([label]) =>
    isWholeWordExtensionMatch({ candidateLabel: label, edgeLabel }),
  );

  if (substringMatch) {
    return substringMatch[1];
  }

  const existingUnmatchedId = unmatchedNodeIds.get(edgeLabel);

  if (existingUnmatchedId) {
    return existingUnmatchedId;
  }

  const unmatchedNodeId = claimUniqueDiagramNodeId({
    baseId: createUnmatchedDiagramNodeId({ label: edgeLabel }),
    takenIds,
  });

  unmatchedNodeIds.set(edgeLabel, unmatchedNodeId);

  return unmatchedNodeId;
}

/**
 * The model only needs to name nodes and describe connections. This
 * builder turns those labels into the public diagram schema by creating
 * stable ids, resolving edge references, and dropping orphan nodes that
 * would otherwise render as disconnected noise in the final visual.
 */
export function buildVisualDiagramOutput({
  edges,
  nodes,
}: AiVisualDiagramOutput): VisualDiagramOutput {
  const takenIds = new Set<string>();
  const allNodes = nodes.map((node, index) => ({
    id: createDiagramNodeId({ index, label: node.label, takenIds }),
    label: node.label,
  }));

  const nodeMap = new Map(allNodes.map((node) => [node.label, node.id]));
  const unmatchedNodeIds = new Map<string, string>();

  const resolvedEdges = edges.map((edge) => ({
    label: edge.label,
    source: resolveNodeId({ edgeLabel: edge.from, nodeMap, takenIds, unmatchedNodeIds }),
    target: resolveNodeId({ edgeLabel: edge.to, nodeMap, takenIds, unmatchedNodeIds }),
  }));

  const referencedIds = new Set(resolvedEdges.flatMap((edge) => [edge.source, edge.target]));

  return {
    edges: resolvedEdges,
    nodes: allNodes.filter((node) => referencedIds.has(node.id)),
  };
}
