import { toSlug } from "@zoonk/utils/string";

type AiVisualDiagramOutput = {
  edges: { from: string; label: string | null; to: string }[];
  nodes: { label: string }[];
};

type VisualDiagramOutput = {
  edges: { label: string | null; source: string; target: string }[];
  nodes: { id: string; label: string }[];
};

/**
 * Edge labels generated by the model often differ slightly from the
 * matching node labels because of casing or partial wording. This
 * resolver tries the obvious matches first and only falls back to a
 * slug when the edge truly points to something missing, which keeps
 * the final diagram usable instead of breaking on minor wording drift.
 */
function isWholeWordExtensionMatch({
  candidateLabel,
  edgeLabel,
}: {
  candidateLabel: string;
  edgeLabel: string;
}): boolean {
  const candidateSlug = toSlug(candidateLabel);
  const edgeSlug = toSlug(edgeLabel);

  return (
    candidateSlug.startsWith(`${edgeSlug}-`) ||
    candidateSlug.endsWith(`-${edgeSlug}`) ||
    edgeSlug.startsWith(`${candidateSlug}-`) ||
    edgeSlug.endsWith(`-${candidateSlug}`)
  );
}

/**
 * Edge labels generated by the model often differ slightly from the
 * matching node labels because of casing or extra leading or trailing
 * words. This resolver tries the obvious matches first and only falls
 * back to a slug when the edge truly points to something missing, which
 * keeps the final diagram usable without letting arbitrary substrings
 * snap to the wrong node.
 */
function resolveNodeId({
  edgeLabel,
  nodeMap,
}: {
  edgeLabel: string;
  nodeMap: Map<string, string>;
}): string {
  const directMatch = nodeMap.get(edgeLabel);

  if (directMatch) {
    return directMatch;
  }

  const normalizedEdgeLabel = edgeLabel.toLowerCase();
  const nodeEntries = [...nodeMap];

  const caseInsensitiveMatch = nodeEntries.find(
    ([label]) => label.toLowerCase() === normalizedEdgeLabel,
  );

  if (caseInsensitiveMatch) {
    return caseInsensitiveMatch[1];
  }

  const substringMatch = nodeEntries.find(([label]) =>
    isWholeWordExtensionMatch({ candidateLabel: label, edgeLabel }),
  );

  return substringMatch?.[1] ?? toSlug(edgeLabel);
}

/**
 * The model only needs to name nodes and describe connections. This
 * builder turns those labels into the public diagram schema by creating
 * stable ids, resolving edge references, and dropping orphan nodes that
 * would otherwise render as disconnected noise in the final visual.
 */
export function buildVisualDiagramOutput({
  edges,
  nodes,
}: AiVisualDiagramOutput): VisualDiagramOutput {
  const allNodes = nodes.map((node) => ({
    id: toSlug(node.label),
    label: node.label,
  }));

  const nodeMap = new Map(allNodes.map((node) => [node.label, node.id]));

  const resolvedEdges = edges.map((edge) => ({
    label: edge.label,
    source: resolveNodeId({ edgeLabel: edge.from, nodeMap }),
    target: resolveNodeId({ edgeLabel: edge.to, nodeMap }),
  }));

  const referencedIds = new Set(resolvedEdges.flatMap((edge) => [edge.source, edge.target]));

  return {
    edges: resolvedEdges,
    nodes: allNodes.filter((node) => referencedIds.has(node.id)),
  };
}
