import {
  type ContentThumbnailParams,
  generateContentThumbnail,
} from "@zoonk/ai/tasks/content/thumbnail";
import { type SafeReturn } from "@zoonk/utils/error";
import { AI_ORG_SLUG } from "@zoonk/utils/org";
import { toSlug } from "@zoonk/utils/string";
import { optimizeImage } from "../images/optimize-image";
import { uploadImage } from "../images/upload-image";

type ContentThumbnailKind = "chapter" | "course" | "lesson";

type GenerateContentThumbnailImageParams = ContentThumbnailParams & {
  kind: ContentThumbnailKind;
  orgSlug?: string;
};

/**
 * Content thumbnail files live under the curriculum level they represent. This
 * keeps future cleanup or browsing by content type simple without making every
 * caller know the exact storage folder names.
 */
function getContentThumbnailFolder(kind: ContentThumbnailKind): string {
  return `${kind}s`;
}

/**
 * Builds the uploaded thumbnail path from stable content metadata. Keeping this
 * outside the AI task makes generated bytes reusable while upload storage adds
 * its own random suffix for collision resistance.
 */
function getContentThumbnailFileName({
  kind,
  orgSlug,
  title,
}: {
  kind: ContentThumbnailKind;
  orgSlug: string | undefined;
  title: string;
}): string {
  const folder = getContentThumbnailFolder(kind);
  const org = orgSlug ?? AI_ORG_SLUG;
  const slug = toSlug(title);

  return `${folder}/${org}/${slug}.webp`;
}

/**
 * Generates, optimizes, and uploads a thumbnail for any curriculum content
 * level. Workflows use this instead of duplicating the image pipeline for
 * courses, chapters, and lessons.
 */
export async function generateContentThumbnailImage({
  kind,
  orgSlug,
  ...params
}: GenerateContentThumbnailImageParams): Promise<SafeReturn<string>> {
  const { data: image, error: imageGenerationError } = await generateContentThumbnail(params);

  if (imageGenerationError) {
    return { data: null, error: imageGenerationError };
  }

  const { data: optimized, error: optimizeError } = await optimizeImage({
    image: Buffer.from(image.uint8Array),
  });

  if (optimizeError) {
    return { data: null, error: optimizeError };
  }

  const fileName = getContentThumbnailFileName({ kind, orgSlug, title: params.title });

  const { data: url, error: uploadError } = await uploadImage({ fileName, image: optimized });

  if (uploadError) {
    return { data: null, error: uploadError };
  }

  return { data: url, error: null };
}
