import { z } from "zod";

const pointSchema = z.tuple([z.number(), z.number()]);

/**
 * The projection a base map was drawn with, so places are projected onto it exactly the way its
 * shapes were. `scale` and `translate` come from fitting the map to its area at build time.
 */
const baseMapProjectionSchema = z.object({
  kind: z.enum(["albersUsa", "azimuthalEqualArea", "conicEqualArea", "equalEarth", "mercator"]),
  parallels: pointSchema.optional(),
  rotate: z.tuple([z.number(), z.number(), z.number()]).optional(),
  scale: z.number(),
  translate: pointSchema,
});

/**
 * How a region is filled: `focus` is what the map is about (Brazil's states), `context` is its
 * surroundings, and the groups tell apart sides or continents (alliances in 1914).
 */
const regionToneSchema = z.enum(["context", "focus", "groupA", "groupB", "groupC"]);

/**
 * A base map drawn ahead of time from public-domain data: SVG paths in a `width` × `height`
 * space, with the labels that help a learner find their way. Generated by
 * `scripts/base-maps/build-base-maps.ts`; never edited by hand.
 */
export const baseMapDrawingSchema = z.object({
  height: z.number(),
  /** Frames around parts drawn apart from the rest, like Alaska and Hawaii. */
  insets: z.array(
    z.object({ height: z.number(), width: z.number(), x: z.number(), y: z.number() }),
  ),
  labels: z.array(
    z.object({
      angle: z.number(),
      /** A message key for names that need translating, like "germanEmpire". */
      key: z.string().nullable(),
      kind: z.enum(["region", "street"]),
      text: z.string(),
      x: z.number(),
      y: z.number(),
    }),
  ),
  /** Which group tones the map uses, for its legend. */
  legend: z.array(z.object({ key: z.string(), tone: regionToneSchema })),
  /** How far the player may zoom in before the drawing looks coarse. */
  maxZoom: z.number(),
  projection: baseMapProjectionSchema,
  regions: z.array(
    z.object({ id: z.string(), name: z.string(), path: z.string(), tone: regionToneSchema }),
  ),
  /** The globe's outline on world maps, drawn as the sea. */
  sphere: z.string().nullable(),
  streets: z.array(z.object({ name: z.string(), path: z.string() })),
  width: z.number(),
});

export type BaseMapDrawing = z.infer<typeof baseMapDrawingSchema>;
export type BaseMapProjection = z.infer<typeof baseMapProjectionSchema>;
export type BaseMapRegionTone = z.infer<typeof regionToneSchema>;
