import { type ProcessIconName } from "@zoonk/core/library/activities/process-icons";
import { type DiagramTone } from "../_assets/diagrams/diagram-types";

/**
 * A color for what the icon stands for (sunlight, water, living things), never for the step's
 * place in the process, so colors can't hint at the order.
 */
export const PROCESS_ICON_TONES: Partial<Record<ProcessIconName, DiagramTone>> = {
  activity: "red",
  apple: "red",
  "arrow-right-left": "teal",
  atom: "purple",
  battery: "lime",
  "battery-charging": "lime",
  beaker: "purple",
  bird: "brown",
  brain: "purple",
  bug: "brown",
  check: "green",
  cloud: "sky",
  "cloud-lightning": "blue",
  "cloud-rain": "sky",
  "cloud-snow": "sky",
  code: "blue",
  coins: "yellow",
  cpu: "blue",
  database: "blue",
  dna: "purple",
  droplet: "sky",
  droplets: "sky",
  earth: "sky",
  egg: "brown",
  factory: "orange",
  feather: "brown",
  filter: "sky",
  fish: "sky",
  flag: "red",
  flame: "orange",
  "flask-conical": "purple",
  flower: "green",
  gem: "purple",
  globe: "sky",
  hammer: "brown",
  heart: "red",
  "heart-pulse": "red",
  key: "yellow",
  leaf: "green",
  lightbulb: "yellow",
  magnet: "purple",
  mail: "blue",
  megaphone: "orange",
  merge: "teal",
  microscope: "purple",
  moon: "blue",
  mountain: "brown",
  "mountain-snow": "brown",
  orbit: "blue",
  package: "brown",
  pickaxe: "brown",
  pill: "red",
  plug: "yellow",
  rabbit: "brown",
  radiation: "purple",
  recycle: "green",
  "refresh-cw": "teal",
  repeat: "teal",
  rocket: "orange",
  satellite: "blue",
  scroll: "brown",
  send: "blue",
  server: "blue",
  shell: "brown",
  ship: "sky",
  snowflake: "sky",
  split: "teal",
  sprout: "green",
  stethoscope: "red",
  sun: "yellow",
  sunrise: "yellow",
  sunset: "yellow",
  syringe: "red",
  telescope: "blue",
  "test-tube": "purple",
  thermometer: "orange",
  "tree-deciduous": "green",
  "tree-pine": "green",
  truck: "brown",
  waves: "sky",
  wheat: "green",
  wind: "sky",
  worm: "green",
  wrench: "brown",
  zap: "yellow",
};
