import { type ProcessIconName } from "@zoonk/core/library/activities/process-icons";
import {
  Activity,
  Apple,
  ArrowRightLeft,
  Atom,
  Baby,
  Banknote,
  Battery,
  BatteryCharging,
  Beaker,
  Bird,
  Bone,
  BookOpen,
  Brain,
  Bug,
  Calculator,
  Check,
  Clock,
  Cloud,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Code,
  Coins,
  Cpu,
  Database,
  Dna,
  Droplet,
  Droplets,
  Earth,
  Egg,
  Eye,
  Factory,
  Feather,
  FileText,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower,
  Footprints,
  Funnel,
  Gauge,
  Gavel,
  Gem,
  Globe,
  Hammer,
  Hand,
  Handshake,
  Heart,
  HeartPulse,
  Hourglass,
  Key,
  Landmark,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  type LucideIcon,
  Magnet,
  Mail,
  Megaphone,
  Merge,
  Microscope,
  Moon,
  Mountain,
  MountainSnow,
  Orbit,
  Package,
  Pencil,
  PersonStanding,
  Pickaxe,
  Pill,
  Plug,
  Rabbit,
  Radiation,
  Rainbow,
  Recycle,
  RefreshCw,
  Repeat,
  Rocket,
  Satellite,
  Scale,
  Scroll,
  Search,
  Send,
  Server,
  Shell,
  Ship,
  ShoppingCart,
  Snowflake,
  Split,
  Sprout,
  Stethoscope,
  Store,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Telescope,
  TestTube,
  Thermometer,
  Timer,
  Tornado,
  Trash,
  TreeDeciduous,
  TreePine,
  Truck,
  Users,
  Utensils,
  Vote,
  WavesHorizontal,
  Wheat,
  Wind,
  Workflow,
  Worm,
  Wrench,
  Zap,
} from "lucide-react";

/** Every icon a process step can name, drawn from Lucide. Core only accepts these names. */
export const PROCESS_ICONS: Record<ProcessIconName, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  "arrow-right-left": ArrowRightLeft,
  atom: Atom,
  baby: Baby,
  banknote: Banknote,
  battery: Battery,
  "battery-charging": BatteryCharging,
  beaker: Beaker,
  bird: Bird,
  bone: Bone,
  "book-open": BookOpen,
  brain: Brain,
  bug: Bug,
  calculator: Calculator,
  check: Check,
  clock: Clock,
  cloud: Cloud,
  "cloud-lightning": CloudLightning,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  code: Code,
  coins: Coins,
  cpu: Cpu,
  database: Database,
  dna: Dna,
  droplet: Droplet,
  droplets: Droplets,
  earth: Earth,
  egg: Egg,
  eye: Eye,
  factory: Factory,
  feather: Feather,
  "file-text": FileText,
  filter: Funnel,
  fish: Fish,
  flag: Flag,
  flame: Flame,
  "flask-conical": FlaskConical,
  flower: Flower,
  footprints: Footprints,
  gauge: Gauge,
  gavel: Gavel,
  gem: Gem,
  globe: Globe,
  hammer: Hammer,
  hand: Hand,
  handshake: Handshake,
  heart: Heart,
  "heart-pulse": HeartPulse,
  hourglass: Hourglass,
  key: Key,
  landmark: Landmark,
  layers: Layers,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  magnet: Magnet,
  mail: Mail,
  megaphone: Megaphone,
  merge: Merge,
  microscope: Microscope,
  moon: Moon,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  orbit: Orbit,
  package: Package,
  pencil: Pencil,
  "person-standing": PersonStanding,
  pickaxe: Pickaxe,
  pill: Pill,
  plug: Plug,
  rabbit: Rabbit,
  radiation: Radiation,
  rainbow: Rainbow,
  recycle: Recycle,
  "refresh-cw": RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  satellite: Satellite,
  scale: Scale,
  scroll: Scroll,
  search: Search,
  send: Send,
  server: Server,
  shell: Shell,
  ship: Ship,
  "shopping-cart": ShoppingCart,
  snowflake: Snowflake,
  split: Split,
  sprout: Sprout,
  stethoscope: Stethoscope,
  store: Store,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  syringe: Syringe,
  telescope: Telescope,
  "test-tube": TestTube,
  thermometer: Thermometer,
  timer: Timer,
  tornado: Tornado,
  trash: Trash,
  "tree-deciduous": TreeDeciduous,
  "tree-pine": TreePine,
  truck: Truck,
  users: Users,
  utensils: Utensils,
  vote: Vote,
  waves: WavesHorizontal,
  wheat: Wheat,
  wind: Wind,
  workflow: Workflow,
  worm: Worm,
  wrench: Wrench,
  zap: Zap,
};
