import Config

# Do not print debug messages in production
config :logger, level: :info

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :zoonk, ZoonkWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures the URL used for external orgs
# E.g. `https://myorg.zoonk.app` should use `https://zoonk.app`
config :zoonk, :external_org_url, System.get_env("EXTERNAL_ORG_URL", "https://zoonk.app")
