import {
  Brain,
  BrainCircuitIcon,
  CalendarCheckIcon,
  ChartNoAxesColumnIncreasingIcon,
  ChartSplineIcon,
  GalleryVerticalEndIcon,
  GaugeIcon,
  Gem,
  Home,
  IdCardLanyard,
  Languages,
  LayoutGrid,
  LifeBuoy,
  LogIn,
  Newspaper,
  NotebookPenIcon,
  PaletteIcon,
  PlusIcon,
  RouteIcon,
  ScrollTextIcon,
  ShieldCheckIcon,
  SmileIcon,
  TargetIcon,
  ZapIcon,
} from "lucide-react";

const menu = {
  activity: { icon: ChartNoAxesColumnIncreasingIcon, url: "/activity" },
  appearance: { icon: PaletteIcon, url: "/settings/appearance" },
  blog: { icon: Newspaper, url: "/blog" },
  buddy: { icon: SmileIcon, url: "/buddy" },
  content: { icon: GalleryVerticalEndIcon, url: "/content" },
  courses: { icon: LayoutGrid, url: "/courses" },
  energy: { icon: ZapIcon, url: "/energy" },
  guardian: { icon: ShieldCheckIcon, url: "/settings/guardian" },
  home: { icon: Home, url: "/" },
  language: { icon: Languages, url: "/language" },
  level: { icon: Brain, url: "/level" },
  logbook: { icon: ScrollTextIcon, url: "/logbook" },
  login: { icon: LogIn, url: "/login" },
  memory: { icon: BrainCircuitIcon, url: "/settings/memory" },
  mistakes: { icon: NotebookPenIcon, url: "/mistakes" },
  myCourses: { icon: LayoutGrid, url: "/my" },
  patterns: { icon: ChartSplineIcon, url: "/patterns" },
  plan: { icon: RouteIcon, url: "/plan" },
  profile: { icon: IdCardLanyard, url: "/profile" },
  progress: { icon: GaugeIcon, url: "/progress" },
  score: { icon: TargetIcon, url: "/score" },
  start: { icon: PlusIcon, url: "/start" },
  subscription: { icon: Gem, url: "/subscription" },
  support: { icon: LifeBuoy, url: "/support" },
  today: { icon: CalendarCheckIcon, url: "/today" },
} as const;

export function getMenu<Key extends keyof typeof menu>(key: Key) {
  return menu[key];
}
