"use cache";

import { getExtracted, setRequestLocale } from "next-intl/server";
import { LearnForm } from "./learn-form";
import type { Metadata } from "next";

export async function generateMetadata({
  params,
}: PageProps<"/[locale]/learn">): Promise<Metadata> {
  const { locale } = await params;
  const t = await getExtracted({ locale });

  return {
    description: t(
      "Tell Zoonk what you want to learn and get a course generated by AI. Start learning any subject with interactive lessons and activities.",
    ),
    title: t("Learn Anything with AI"),
  };
}

export default async function Learn({ params }: PageProps<"/[locale]/learn">) {
  const { locale } = await params;
  setRequestLocale(locale);

  const t = await getExtracted();

  return (
    <main className="mx-auto flex w-full max-w-xl flex-1 flex-col items-center justify-center gap-4 p-4">
      <h1
        className="text-foreground/90 md:tracking-tightest pt-4 text-center text-2xl font-semibold -tracking-wide md:pt-8 md:text-3xl md:-tracking-wider"
        id="learn-title"
      >
        {t("What do you want to learn?")}
      </h1>

      <LearnForm />
    </main>
  );
}
