"use cache";

import { cacheTagLearn } from "@zoonk/utils/cache";
import type { Metadata } from "next";
import { cacheLife, cacheTag } from "next/cache";
import { getExtracted, setRequestLocale } from "next-intl/server";
import { StartCourseForm } from "./start-course-form";

export async function generateMetadata({
  params,
}: PageProps<"/[locale]/learn">): Promise<Metadata> {
  const { locale } = await params;

  cacheLife("max");
  cacheTag(locale, cacheTagLearn());

  const t = await getExtracted({ locale });

  return {
    description: t(
      "Tell Zoonk what you want to learn and get a course generated by AI. Start learning any subject with interactive lessons and activities.",
    ),
    title: t("Learn Anything with AI"),
  };
}

export default async function Learn({ params }: PageProps<"/[locale]/learn">) {
  const { locale } = await params;
  setRequestLocale(locale);

  cacheLife("max");
  cacheTag(locale, cacheTagLearn());

  const t = await getExtracted();

  return (
    <main className="mx-auto flex w-full max-w-xl flex-1 flex-col items-center justify-center gap-4 p-4">
      <h1
        className="-tracking-wide md:-tracking-wider pt-4 text-center font-semibold text-2xl text-foreground/90 md:pt-8 md:text-3xl md:tracking-tightest"
        id="learn-title"
      >
        {t("What do you want to learn?")}
      </h1>

      <StartCourseForm />
    </main>
  );
}
