"use client";

import {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldLabel,
} from "@zoonk/ui/components/field";
import { Input } from "@zoonk/ui/components/input";
import { cn } from "@zoonk/ui/lib/utils";
import { SubmitButton } from "@zoonk/ui/patterns/buttons/submit";
import { createContext, use, useActionState, useId } from "react";

export type WaitlistState = { status: "idle" | "error" | "success" };

export type WaitlistAction = (
  prevState: WaitlistState,
  formData: FormData,
) => Promise<WaitlistState>;

const INITIAL_WAITLIST_STATE: WaitlistState = { status: "idle" };

type WaitlistContextValue = { state: WaitlistState };
type WaitlistFieldContextValue = { inputId: string };

const WaitlistContext = createContext<WaitlistContextValue | null>(null);
const WaitlistFieldContext = createContext<WaitlistFieldContextValue | null>(null);

/**
 * Gives waitlist child components access to the latest submission state without
 * making every future waitlist page pass status props through its field tree.
 */
function useWaitlistContext(): WaitlistContextValue {
  const context = use(WaitlistContext);

  if (!context) {
    throw new Error("Waitlist components must be used inside WaitlistForm");
  }

  return context;
}

/**
 * Shares one generated input id between a field label and whichever control the
 * page composes inside that field.
 */
function useWaitlistFieldContext(): WaitlistFieldContextValue {
  const context = use(WaitlistFieldContext);

  if (!context) {
    throw new Error("Waitlist field components must be used inside WaitlistField");
  }

  return context;
}

/**
 * Owns server-action state for waitlist forms while leaving the actual fields
 * and explanatory copy to each page that composes the form.
 */
export function WaitlistForm({
  action,
  children,
  className,
}: {
  action: WaitlistAction;
  children: React.ReactNode;
  className?: string;
}) {
  const [state, formAction] = useActionState(action, INITIAL_WAITLIST_STATE);

  return (
    <WaitlistContext value={{ state }}>
      <form action={formAction} className={cn("flex w-full flex-col gap-6", className)}>
        {children}
      </form>
    </WaitlistContext>
  );
}

/**
 * Creates one accessible form field boundary so labels, controls, descriptions,
 * and errors can be reordered without losing their shared input id.
 */
export function WaitlistField({ children, className }: React.ComponentProps<"div">) {
  const inputId = useId();

  return (
    <WaitlistFieldContext value={{ inputId }}>
      <Field className={className}>
        <FieldContent>{children}</FieldContent>
      </Field>
    </WaitlistFieldContext>
  );
}

/**
 * Labels the control inside the nearest waitlist field using the field id
 * generated by `WaitlistField`.
 */
export function WaitlistFieldLabel({ children, className }: React.ComponentProps<"label">) {
  const { inputId } = useWaitlistFieldContext();

  return (
    <FieldLabel className={className} htmlFor={inputId}>
      {children}
    </FieldLabel>
  );
}

/**
 * Renders the standard single-line waitlist control while preserving the
 * accessible label relationship owned by the field wrapper.
 */
export function WaitlistInput({ className, ...props }: React.ComponentProps<"input">) {
  const { inputId } = useWaitlistFieldContext();

  return <Input className={className} id={inputId} {...props} />;
}

/**
 * Keeps helper copy visually aligned with the shared field primitives.
 */
export function WaitlistFieldDescription({ children, className }: React.ComponentProps<"p">) {
  return <FieldDescription className={className}>{children}</FieldDescription>;
}

/**
 * Shows the latest waitlist submission result in one stable place so each page
 * can define its own success and error copy without duplicating action-state
 * branching.
 */
export function WaitlistStatus({
  errorMessage,
  successMessage,
}: {
  errorMessage: string;
  successMessage: string;
}) {
  const { state } = useWaitlistContext();

  if (state.status === "success") {
    return (
      <p aria-live="polite" className="text-success text-sm font-medium">
        {successMessage}
      </p>
    );
  }

  if (state.status === "error") {
    return <FieldError>{errorMessage}</FieldError>;
  }

  return null;
}

/**
 * Uses the shared pending-button behavior for all waitlist forms so retries and
 * slow submissions feel the same wherever the pattern appears.
 */
export function WaitlistSubmit({ children, ...props }: React.ComponentProps<typeof SubmitButton>) {
  return <SubmitButton {...props}>{children}</SubmitButton>;
}
