import { writeFileSync } from "node:fs";
import { join } from "node:path";

/**
 * Converts an HTTP URL to Xcode's configuration syntax. An unescaped `//` starts an xcconfig comment, while an empty build-setting expansion preserves the two URL slashes in the resolved value.
 */
function getXcodeConfigurationURL(apiUrl: string): string {
  return apiUrl.replace("://", ":/$()/");
}

/**
 * Gives Debug builds the same clone- or worktree-specific API origin that `pnpm dev` already resolves for the web apps, eliminating per-scheme setup without checking a machine-specific value into Git.
 */
export function writeAppleDevelopmentConfiguration({
  apiUrl,
  currentDirectory,
}: {
  apiUrl: string;
  currentDirectory: string;
}): void {
  const configurationPath = join(currentDirectory, "apps/apple/Configuration/Local.xcconfig");
  const xcodeURL = getXcodeConfigurationURL(apiUrl);

  writeFileSync(
    configurationPath,
    `// Generated by pnpm dev. Do not edit.\nZOONK_DEVELOPMENT_API_BASE_URL = ${xcodeURL}\n`,
  );
}
