name: Check Translations

permissions:
  contents: read

on: push

jobs:
  i18n-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11.6.0
          run_install: true

      - name: Check for i18n errors
        run: pnpm eloqnt:lint
