name: Check Translations

permissions:
  contents: read

on: push

jobs:
  i18n-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check for i18n errors
        run: pnpm eloqnt:lint
